---
title: "Height versus Weight"
subtitle: "Predicting Height from Weight Using Tidymodels"
author: "John Karuitha"
date: "`r Sys.Date()`"
output:
  rmdformats::material:
    highlight: kate
    code_folding: hide
---


```{r setup, include=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=TRUE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

## **Background**

```{r}
## Load required libraries
library(dslabs)
library(tidymodels)

## Load the data
data("heights")

heights$sex <- factor(heights$sex, levels = c("Male", "Female"))

## View data
head(heights)
nrow(heights)
```

## Train/Test Split

```{r}
split_object <- initial_split(heights, prop = 0.7, strata = sex)

height_train <- split_object %>% training()

height_test <- split_object %>% testing()
```


## Set Regression Model

```{r}
linear_mode <- linear_reg() %>% 
    
    set_engine("lm") %>% 
    
    set_mode("regression")
```

## Fit Regression Model

```{r}
my_regression_fit <- linear_mode %>% 
    
    fit(height ~ sex, data = height_train)

broom::tidy(my_regression_fit)
```

## Predict on test set 

```{r}
my_height_predicition <- my_regression_fit %>% 
    
    predict(new_data = height_test) %>% 
    
    bind_cols(height_test)

my_height_predicition
```

## Evaluate the Model

```{r}
my_height_predicition %>% 
    
    rmse(truth = height, estimate = .pred)

my_height_predicition %>% 
    
    rsq(truth = height, estimate = .pred)
```

## The Shorter Route

```{r}
final_fit <- linear_mode %>% 
    
    last_fit(height ~ factor(sex), split = split_object)

final_fit %>% collect_predictions()

final_fit %>% collect_metrics()
```

